// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpxknwstcumorptnrddh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRweGtud3N0Y3Vtb3JwdG5yZGRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1ODQ4MjMsImV4cCI6MjA2NjE2MDgyM30.x6egpwdE_40Vwmz6QrD-WGAvQqa0XIQ09rQImG4mpzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);